# SEASSION 4 --------------=====//////////////////////////

In [17]:
import warnings

In [18]:
warnings.filterwarnings("ignore")

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("ML-3 Feature Encoding Resource16931320640.txt")

In [3]:
data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

# Ordinal Encoding

In [12]:
l = ["none","high","low","very high","medium"]  #Manual Way

In [13]:
Data = pd.DataFrame(l,columns=["TYPE"])

In [14]:
a = [0,3,1,4,2]

In [15]:
Data["en_values"] = # a

SyntaxError: invalid syntax (2464490534.py, line 1)

In [10]:
Data

        TYPE  en_values
0       none          0
1       high          3
2        low          1
3  very high          4
4     medium          2

In [19]:
Data.replace(l,a)

   TYPE
0     0
1     3
2     1
3     4
4     2

# Label Encoding

In [20]:
l = ["jaipur","surat","delhi","goa","jaipur","surat","delhi","goa","jaipur","surat","delhi","goa"]

In [24]:
Data = pd.DataFrame(l,columns=["city"])

In [25]:
Data

      city
0   jaipur
1    surat
2    delhi
3      goa
4   jaipur
5    surat
6    delhi
7      goa
8   jaipur
9    surat
10   delhi
11     goa

In [23]:
from sklearn.preprocessing import LabelEncoder

In [29]:
laben = LabelEncoder()

In [31]:
laben.fit_transform(Data["city"])

array([2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1])

In [32]:
Data["Label_Encode_City"] = laben.fit_transform(Data["city"])

In [34]:
Data.head(2)

     city  Label_Encode_City
0  jaipur                  2
1   surat                  3

In [38]:
Data.drop("city",axis=1,inplace=True)

In [39]:
Data

    Label_Encode_City
0                   2
1                   3
2                   0
3                   1
4                   2
5                   3
6                   0
7                   1
8                   2
9                   3
10                  0
11                  1

In [44]:
# method 1 to check what is data on that number 
laben.inverse_transform([1,2])

array(['goa', 'jaipur'], dtype=object)

In [45]:
# check full column decoding 

laben.inverse_transform(Data["Label_Encode_City"])

array(['jaipur', 'surat', 'delhi', 'goa', 'jaipur', 'surat', 'delhi',
       'goa', 'jaipur', 'surat', 'delhi', 'goa'], dtype=object)

# One Hot Encoding

In [47]:
l = ["jaipur","surat","delhi","goa","jaipur","surat","delhi","goa","jaipur","surat","delhi","goa"]

In [48]:
Data = pd.DataFrame(l,columns=["city"])

In [49]:
Data["city"].unique()

array(['jaipur', 'surat', 'delhi', 'goa'], dtype=object)

In [50]:
Data.describe()

          city
count       12
unique       4
top     jaipur
freq         3

In [52]:
data = pd.get_dummies(Data["city"])

In [53]:
data

    delhi    goa  jaipur  surat
0   False  False    True  False
1   False  False   False   True
2    True  False   False  False
3   False   True   False  False
4   False  False    True  False
5   False  False   False   True
6    True  False   False  False
7   False   True   False  False
8   False  False    True  False
9   False  False   False   True
10   True  False   False  False
11  False   True   False  False

In [66]:
data["city"] = l

In [67]:
data

    delhi    goa  jaipur  surat    city
0   False  False    True  False  jaipur
1   False  False   False   True   surat
2    True  False   False  False   delhi
3   False   True   False  False     goa
4   False  False    True  False  jaipur
5   False  False   False   True   surat
6    True  False   False  False   delhi
7   False   True   False  False     goa
8   False  False    True  False  jaipur
9   False  False   False   True   surat
10   True  False   False  False   delhi
11  False   True   False  False     goa

In [68]:
data.drop("city",axis=1,inplace=True)

In [69]:
data

    delhi    goa  jaipur  surat
0   False  False    True  False
1   False  False   False   True
2    True  False   False  False
3   False   True   False  False
4   False  False    True  False
5   False  False   False   True
6    True  False   False  False
7   False   True   False  False
8   False  False    True  False
9   False  False   False   True
10   True  False   False  False
11  False   True   False  False

In [70]:
data = pd.read_csv("ML-3 Feature Encoding Resource16931320640.txt")

In [71]:
data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [73]:
data["marital-status"].unique()

array(['Never-married', 'Married-civ-spouse', 'Widowed', 'Divorced',
       'Separated', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [ ]:
#Label encoding approach we have long data and unordered

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [74]:
encode = LabelEncoder()

In [76]:
data["marital-status"] = encode.fit_transform(data["marital-status"])

In [78]:
#  now for education we use ordinal encoding because we need data in ordered way

In [79]:
data["education"].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [81]:
data["education"] = data["education"].replace(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', 'Doctorate',
       '5th-6th', 'Assoc-voc', '9th', '12th', '1st-4th', 'Preschool'],[7, 9, 12, 10, 6, 15, 4, 13, 14, 16, 3, 11, 5, 8, 2, 1]
)

In [82]:
data

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,7,7,4,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,9,9,2,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,12,12,2,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,10,10,2,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,10,10,4,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,12,12,2,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,9,9,2,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,9,9,6,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,9,9,4,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,9,9,2,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K